version: '3'

services:

  application:
    image: ${PROJECT}:${GIT_LOCAL_BRANCH}
    container_name: ${PROJECT}
    env_file: ./app/.env
    build:
      context: ./app
      dockerfile: Dockerfile.production
    ports:
      - "4000:4000"
    expose:
      - "4000"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/dist
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: ${PROJECT}-postgres:${GIT_LOCAL_BRANCH}
    container_name: ${PROJECT}-postgres
    build:
      context: ./.docker/postgres
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_MULTIPLE_DATABASES="${DB_DATABASE}","${DB_TEST_DATABASE}"
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./.docker/postgres:/docker-entrypoint-initdb.d
    networks:
      - backend

networks:
  backend:
    driver: "bridge"
    
volumes:
  postgres:
